### ISSUE TITLE
Make notation consitent with "standard"

### ISSUE THREAD

**Issue by chfin** [DCMLab/pitchtypes#9]
There are some of inconsistencies with the draft of the ["standard"](https://hackmd.io/dmKfG1SbTWKlJp3svZ8y2A). We should either fix them here or, if there is a good reason, change them in the draft.
- [x] octaves are separated by `+/-` instead of `:`, i.e. `M2+3` instead of `M2:3`, and `P4-2` instead of `P4:-2`. (update: standard to be changed to `:`)
- [ ] intervals don't take a `+` sign (`m2` instead of `+m2`). Augmented and diminished intervals are distinguished from pitches by case, i.e. `A4` (pitch) vs `a4` (interval). (When the type is clear, a parser may be case insensitive, e.g. when a type specific parsing function is called.)
- [ ] perfect intervals should written using `P`, not `p`
- [ ] (less important) allow unicode flats and sharps as alternatives to `b` and `#`.

**Comment by robert-lieck** [comment]
Yes! I like using case to distinguish intervals and pitches, I'm happy to change that in this library. Also for the unicode flats and sharps, I think that's a nice feature (I opened a separate issue for that #10).

Concerning the leading `+`/`-` for intervals and the separation of the octave: As @fabianmoss mentioned in the zoom meeting, people with a musical background will frequently think of intervals as being undirected. Whereas here they are always directed (with `abs` being used to get their magnitude). So always having a leading `+`/`-` avoids misunderstandings. But it's of course also more verbose, I agree on that.

The question of how the octave should be separated for me kind of depends on the leading `+`/`-` question: Without leading `+`/`-` is fine to use `+`/`-` to separate the octave, otherwise it looks somewhat ugly (`+a4+2`). By the way, does something like `+m2-2` make sense? That is, can the direction and the octave have different sign? I think not, or can it?

Another question: Should the separation between class name and octave be the same for pitches and intervals? I guess, theoretically yes, but something like `C:4` or `C+4` does not correspond to common notation for pitches. While  for intervals, we need some kind of separator because they end in a number.

**Comment by robert-lieck** [comment]
Btw I'm in favor of enforcing an unambiguous spelling: Any specific string should only be a valid representation of exactly one object (at least for the same base type). This avoids confusion:
 * Why are some things printed differently from how they are initialised?
 * Why can or cannot I initialise the same thing differently depending on the context?
But I think a "sloppy parsing" flag could be added, so that people can consciously opt-in on that, to still provide the convenience.

**Comment by chfin** [comment]
Mh, the direction thing is genrally a good question. I the other libraries I allow two notations for a minor third down: `-m3+0` and `M6-1`, where the first is the canonical one. We could also restrict the octaves to be positive, then the second notation becomes invalid, and negative intervals must always be notated using a `-` sign. I guess that's probably a good idea. In that case, `:oct` would work too, although using `+` would make the idea of "adding" octaves clearer, I think. E.g. `M2+1` is a bit more intuitive than `M2:1`. But then again, it's not clear if `-M2+1` should be read as `-(M2+1)` or `(-M2)+1` (currently the former is correct), and `:` might avoid that.

For pitches I wouldn't use the separator, since a) we don't need it for parsing and b) it's not used in standard notation. In the interval case, I'm not aware of any standard notation for things like `P4+3`.

Regarding directedness, I think once you start doing interval arithmetics, you are forced to think about directions anyway, and then I think that having the default to be "upwards" is what people would expect (since it works the same for numbers). So I don't think it's necessary to indicate the direction using "+", but we could make it optional for parsing.

**Comment by fabianmoss** [comment]
I would be in favor of using the standard notation and terminology of set theory. A good summary can be found in Straus (2005). Introduction to Post-Tonal Theory.

**Comment by robert-lieck** [comment]
> I would be in favor of using the standard notation and terminology of set theory

Could you briefly state what that would be for the cases discussed here?

**Comment by chfin** [comment]
> Btw I'm in favor of enforcing an unambiguous spelling

yes, me generally too. I also like the idea of a "sloppy" flag, although I wonder whether it should be turned on by default. E.g. when parsing from a separate source, chances are high that you can parse at least pitches with a sloppy default, but for interactive coding etc. you might get the problems that you described above.

**Comment by robert-lieck** [comment]
> I wonder whether it should be turned on by default

I'd suggest to have it off by default but to provide meaningful error messages that suggest turning it on. That makes sure errors don't pass by unnoticed but also a noob fails at most once (if they read the error messages 😄).

**Comment by chfin** [comment]
yes, good idea. Could also be told like that in a tutorial. "By default this library will enforce strict notation so that errors are caught early on. If you try to apply it to external data, you might want to use the 'sloppy' option."

**Comment by chfin** [comment]
I found another one: perfect intervals should be written with an uppercase 'P', which is closer to the [standard notation](https://en.wikipedia.org/wiki/Interval_(music)#Perfect) (the only exception is then a lowercase 'a' for augmented, which is done to be able to distinguish the interval `a4` from the pitch `A4`). This is also the way perfect intervals are written in the other libraries.

**Comment by chfin** [comment]
Also I'm going to remove the separator issue, I think this is settled as `:` now, right?

**Comment by robert-lieck** [comment]
For the upper/lower case I am not sure what the best solution is. I don't think counting the percentage of cases, in which it conforms to the standard, it the right measure. It definitely makes a difference but I think consistency is more important. So 100% conformity to the (or at least some) standard would be best, but otherwise I tend to favour the consistency of an all-lower-case notation. Then there is one single rule: pitches are upper-case, intervals are lower-case.

Maybe we should do another poll with two examples that may be a particularly well suited case for checking whether the notation is intuitive: `A4 + d5 = P1` and `A4 - D5 = -P4:0` (in standard notation). Then we have four options:
1. lower-case intervals: consistent capitalisation but `a4` and `p1` inconsistent with standard
   - `a4 + d5 = p1` and `A4 - D5 = -p4:0`
2. mixed-case intervals: inconsistent capitatisation but only `a4` inconsistent with standard
   - `a4 + d5 = P1` and `A4 - D5 = -P4:0`
3. signed intervals: capitalisation fully consistent with standard but sign-prefixes everywhere
   - `+A4 + +d5 = +P1` and `A4 - D5 = -P4:0`
4. sloppy: ambiguity for `A4` but otherwise easy-to-read and compliant with standard
   -  `A4 + d5 = P1` and `A4 - D5 = -P4:0` (but also `A4 + d5:0 = Eb5`)

What do you think? @chfin, I think you also made a very good point that this kind of arithmetic notation does not actually occur anywhere. So the ugly case no 4 does not in fact appear, which makes it an acceptable alternative to me, as it is unambiguous and at the same time fully compliant with standard notation.

Also, @fabianmoss, you suggested to follow _Straus (2005). Introduction to Post-Tonal Theory_. Do you have a digital copy of that book, which we could have a look into? Or could you comment on how notation would look like according to them?

**Comment by chfin** [comment]
I don't know, I think the notation is generally fine, it's just about  `P1` vs `p1`. For intervals you need both upper and lowercase anyway to distinguish major and minor, so completely lowercase doesn't work. `P1` is the variant that is standard notation, but I mainly brought it up because it complies to the description of the format in the [suggested standard](https://hackmd.io/dmKfG1SbTWKlJp3svZ8y2A) and because it [already has been in use for quite some time](https://github.com/DCMLab/schema_annotation_data/blob/master/data/lexicon.json). I also think there is nothing that really speaks against it.

**Comment by fabianmoss** [comment]
...well this was before I talked with Christoph about what the purpose of pitchtypes actually is. I think that the reference is not really useful for you. Rather, I would suggest to do a survey how notes and intervals are represented in e.g. music21, **kern, MuseScore, MEI, etc.

**Comment by chfin** [comment]
Just for completeness, it's not only the interval-class notation that is already in use but also the pitch notation (see, e.g. [here](https://github.com/DCMLab/schema_annotation_data/tree/master/data/mozart_sonatas/notelist)). This is *published data* so I would be strongly in favor of not changing the notation unless there is a very good reason to do so (fortunately this is not affected by the `:` vs `+` thing).

**Comment by robert-lieck** [comment]
OK, these are good reasons to at least support that convention. I am planning to add class-level print options anyway (e.g. to allow for unicode ♭/♯ with the option to switch back to b/# for terminals that don't support unicode), which could also be extended to parsing options. So I don't see a problem with supporting that convention or maybe even making it the default.

**Comment by robert-lieck** [comment]
> I would suggest to do a survey how notes and intervals are represented in e.g. music21, **kern, MuseScore, MEI, etc.

This sounds reasonable, but I personally will not get around doing this any time soon. But any input is of course highly welcome. (Studentproject?)

**Comment by robert-lieck** [comment]
I think the central points are now implemented
- octaves are separated by ':'
- intervals are not printed with a leading `+` (but it is accepted for parsing)
- augmented/diminished intervals are lower case (`a4` etc)
- perfect intervals are upper case (`P5` etc)
- unicode flats and sharps are not central for standard conformity and have their own issue #10

But this thread still contains a number of interesting discussion points, so not sure about closing it

**Comment by chfin** [comment]
cool, sounds good. I guess unicode parsing would be very useful and easy to implement, so we should probably do it soon (printing is not so essential). Since the original problems are addressed, I'd close the issue now. If needed, we can still refer back to it, but I think most of the discussion points have been resolved anyways.

**Comment by chfin** [comment]
We could open new enhancement issues for some of the points though, e.g. import from kern notation or music21 classes.

**Comment by robert-lieck** [comment]
> I guess unicode parsing would be very useful and easy to implement

Parsing is implemented in c2312559ed50c95128fc0272a2e76122b4be9199 now (printing not yet)
